server:
  port: 8080

spring:
  web:
    resources:
      static-locations:
        - file:uploads/
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth
          uri: ${AUTH_URI:http://autenticacion-servicio:8081}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: users
          uri: ${USERS_URI:http://usuarios-servicio:8082}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: products
          uri: ${PRODUCTS_URI:http://productos-servicio:8083}
          predicates:
            - Path=/api/products/**
          filters:
            - RewritePath=^/api/products(?<segment>/?.*), /productos${segment}
        - id: orders
          uri: ${ORDERS_URI:http://orders-servicio:8089}
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=^/api/orders(?<segment>/?.*), /pedidos${segment}
        - id: payments
          uri: ${PAYMENTS_URI:http://payments-servicio:8085}
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=2
        - id: inventory
          uri: ${INVENTORY_URI:http://inventory-servicio:8086}
          predicates:
            - Path=/api/inventario/**
          filters:
            - StripPrefix=2
        - id: notifications
          uri: ${NOTIFICATIONS_URI:http://notifications-servicio:8087}
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=2
  webflux:
    cors:
      enabled: true

jwt:
  secreto: ${JWT_SECRET:ZGV2LXNlY3JldC1rZXktMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=}
