version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql-auth:
    image: mysql:8
    container_name: mysql-auth
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_db
    ports:
      - "33061:3306"

  mysql-users:
    image: mysql:8
    container_name: mysql-users
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users_db
    ports:
      - "33062:3306"

  mysql-products:
    image: mysql:8
    container_name: mysql-products
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products_db
    ports:
      - "33063:3306"

  mysql-orders:
    image: mysql:8
    container_name: mysql-orders
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orders_db
    ports:
      - "33064:3306"

  mysql-payments:
    image: mysql:8
    container_name: mysql-payments
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=payments_db
    ports:
      - "33065:3306"

  mysql-inventory:
    image: mysql:8
    container_name: mysql-inventory
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=inventory_db
    ports:
      - "33066:3306"

  mysql-notifications:
    image: mysql:8
    container_name: mysql-notifications
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notifications_db
    ports:
      - "33067:3306"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - rabbitmq
      - auth-service
      - users-service
      - products-service
      - orders-service
      - payments-service
      - inventory-service
      - notifications-service
    env_file:
      - ./api-gateway/.env
    ports:
      - "8080:8080"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - rabbitmq
      - mysql-auth
    env_file:
      - ./auth-service/.env
    ports:
      - "8081:8081"

  users-service:
    build: ./users-service
    container_name: users-service
    depends_on:
      - rabbitmq
      - mysql-users
    env_file:
      - ./users-service/.env
    ports:
      - "8082:8082"

  products-service:
    build: ./products-service
    container_name: products-service
    depends_on:
      - rabbitmq
      - mysql-products
    env_file:
      - ./products-service/.env
    ports:
      - "8083:8083"

  orders-service:
    build: ./orders-service
    container_name: orders-service
    depends_on:
      - rabbitmq
      - mysql-orders
    env_file:
      - ./orders-service/.env
    ports:
      - "8084:8084"

  payments-service:
    build: ./payments-service
    container_name: payments-service
    depends_on:
      - rabbitmq
      - mysql-payments
    env_file:
      - ./payments-service/.env
    ports:
      - "8085:8085"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      - rabbitmq
      - mysql-inventory
    env_file:
      - ./inventory-service/.env
    ports:
      - "8086:8086"

  notifications-service:
    build: ./notifications-service
    container_name: notifications-service
    depends_on:
      - rabbitmq
      - mysql-notifications
    env_file:
      - ./notifications-service/.env
    ports:
      - "8087:8087"
