server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

security:
  jwt:
    secret: ${JWT_SECRET:ZmFrZV9zZWNyZXRfZm9yX2Rldl9vbmx5X2RvX25vdF91c2VfaW5fcHJvZA==}
    exp-minutes: 30

events:
  exchange:
    users: ${USERS_EXCHANGE:users.events}
outbox:
  publisher:
    delay-ms: ${OUTBOX_PUBLISH_DELAY_MS:2000}
